# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: plan-your-trip-api dev

on:
  push:
    branches:
      - development
    paths: 
      - 'src/backend/TripPlanner.Api'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.301'

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/plan-your-trip-api-dev

  test:
    runs-on: windows-latest
    needs: [build]
    steps: 
    - name: Test
      run: dotnet test

  deploy:
    runs-on: windows-latest
    needs: [build, test]

    steps:
    - name: Deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: plan-your-trip-api
        publish-profile: ${{ secrets.plan_your_trip_api_dev_azure_profile }}
        package: ${{env.DOTNET_ROOT}}/plan-your-trip-api-dev


