# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: plan-your-trip-api dev

on:
  pull-request:
    branches:
      - development
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.301'

    - name: Install dependencies
      run: dotnet restore 'src/backend/TripPlanner.Api' | dotnet restore 'src/backend/TripPlanner.Api' | npm install 'src/frontend' | npm list --depth=1

    - name: Build Api
      run: dotnet build 'src/backend/TripPlanner.Api' --configuration Release --no-restore
    - name: Build Auth
      run: dotnet build 'src/backend/TripPlanner.Auth' --configuration Release --no-restore
    - name: Build frontend
      run: npm run build --prefix 'src/frontend'

    - name: Test Api
      run: dotnet test 'src/backend/TripPlanner.Api' --no-restore --verbosity normal
    - name: Test Auth
      run: dotnet test 'src/backend/TripPlanner.Auth' --no-restore --verbosity normal

