name: plan-your-trip-api push-dev

on:
  push:
    branches:
      - development
    paths:
      - 'src/backend/TripPlanner.Api'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.301'

    - name: Install dependencies
      run: dotnet restore 'src/backend/TripPlanner.Api'

    - name: Build
      run: dotnet build 'src/backend/TripPlanner.Api' --configuration Release --no-restore

  test:
    runs-on: windows-latest
    needs: [build]
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.301'

    - name: Install dependencies
      run: dotnet restore 'src/backend/TripPlanner.Api'
    - name: Test
      run: dotnet test 'src/backend/TripPlanner.Api' --no-restore --verbosity normal

  deploy:
    runs-on: windows-latest
    needs: [build, test]
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.301'

    - name: Publish
      run: dotnet publish 'src/backend/TripPlanner.Api' -c Release -o ${{env.DOTNET_ROOT}}/plan-your-trip-api-dev

    - name: Deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: plan-your-trip-api-dev
        publish-profile: ${{ secrets.plan_your_trip_api_dev_azure_profile }}
        package: ${{env.DOTNET_ROOT}}/plan-your-trip-api-dev
